const {test,beforeEach}=require('node:test');
const assert=require('node:assert/strict');
const ts=require('typescript'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module');
let smtpCalls=0,lastMail,mode='ok',counts=new Map(),used=new Set(),verifyCalls=0;
function load(file,overrides={}){const filename=path.resolve(file),m=new Module(filename);m.paths=module.paths;const original=m.require.bind(m);m.require=id=>overrides[id]||original(id);m._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true,target:ts.ScriptTarget.ES2020}}).outputText,filename);return m.exports;}
const security=load('lib/candidatura-security.ts');
const {POST}=load('app/api/candidatura/route.ts',{'@/lib/candidatura-security':security,nodemailer:{createTransport:()=>({sendMail:async mail=>{smtpCalls++;lastMail=mail;return {accepted:['levelup.cef@gmail.com']}}})}});
beforeEach(()=>{smtpCalls=0;verifyCalls=0;counts=new Map();used=new Set();mode='ok';Object.assign(process.env,{VERCEL:'1',UPSTASH_REDIS_REST_URL:'https://redis.test',UPSTASH_REDIS_REST_TOKEN:'redis-secret',RATE_LIMIT_IP_SALT:'test-salt',TURNSTILE_SECRET_KEY:'turnstile-secret',TURNSTILE_ALLOWED_HOSTNAMES:'eden.test',SMTP_HOST:'mock',SMTP_USER:'mock@example.com',SMTP_PASS:'mock'});
 global.fetch=async(url,options)=>{if(url==='https://redis.test'){if(mode==='redis-down')throw Error('offline');const command=JSON.parse(options.body);assert.equal(command[0],'EVAL');assert.match(command[1],/INCR/);assert.match(command[1],/EXPIRE/);assert.match(command[1],/900/);assert.ok(!command[3].includes('203.0.113'));const n=(counts.get(command[3])||0)+1;counts.set(command[3],n);return Response.json({result:n});}
 assert.equal(url,'https://challenges.cloudflare.com/turnstile/v0/siteverify');verifyCalls++;if(mode==='turnstile-down')throw Error('offline');assert.equal(options.body.get('secret'),'turnstile-secret');const token=options.body.get('response');const success=mode!=='invalid'&&!used.has(token);used.add(token);return Response.json({success,hostname:mode==='wrong-host'?'evil.test':'eden.test',action:mode==='wrong-action'?'other':'candidatura'});};});
let sequence=0;
function request({ip='203.0.113.1',honeypot='',token=`token-${++sequence}`,files=0,bad=false,size=0,message='',email='test@example.com'}={}){const data=new FormData();data.set('name','Test');data.set('phone','3330000000');data.set('email',email);data.set('message',message);data.set('company_website',honeypot);if(token!==null)data.set('cf-turnstile-response',token);for(let i=0;i<files;i++)data.append('photos',new Blob([bad?'bad':Buffer.from([255,216,255,224]),Buffer.alloc(size)],{type:'image/jpeg'}),'foto.jpg');return new Request('https://eden.test/api/candidatura',{method:'POST',headers:{origin:'https://eden.test','x-forwarded-for':ip},body:data});}
test('valid optional message and 4 photos reach unchanged SMTP recipient',async()=>{assert.equal((await POST(request({files:4}))).status,200);assert.equal(smtpCalls,1);assert.equal(lastMail.to,'levelup.cef@gmail.com');assert.equal(lastMail.attachments.length,4);assert.match(lastMail.text,/Non inserito/);});
test('sixth attempt blocked; a different IP retains its quota',async()=>{for(let i=0;i<5;i++)assert.equal((await POST(request())).status,200);assert.equal((await POST(request())).status,429);assert.equal(smtpCalls,5);assert.equal((await POST(request({ip:'203.0.113.2'}))).status,200);});
test('honeypot discards without verification or SMTP',async()=>{assert.equal((await POST(request({honeypot:'spam'}))).status,400);assert.equal(verifyCalls,0);assert.equal(smtpCalls,0);});
for(const failure of ['invalid','wrong-host','wrong-action','turnstile-down','redis-down'])test(failure+' fails closed',async()=>{mode=failure;assert.notEqual((await POST(request())).status,200);assert.equal(smtpCalls,0);});
test('missing token and replay are rejected',async()=>{assert.equal((await POST(request({token:null}))).status,400);assert.equal((await POST(request({token:'same'}))).status,200);assert.equal((await POST(request({token:'same'}))).status,400);assert.equal(smtpCalls,1);});
test('missing secret or Redis config fails closed',async()=>{delete process.env.TURNSTILE_SECRET_KEY;assert.equal((await POST(request())).status,400);delete process.env.UPSTASH_REDIS_REST_TOKEN;assert.equal((await POST(request())).status,503);assert.equal(smtpCalls,0);});
test('existing field, file count, type and 3 MB limits preserved',async()=>{for(const options of [{email:'bad'},{message:'a'.repeat(2001)},{files:5},{files:1,bad:true},{files:1,size:3*1024*1024}])assert.notEqual((await POST(request(options))).status,200);assert.equal(smtpCalls,0);});
test('large body rejected even without Content-Length',async()=>{const original=request({files:1,size:4*1024*1024});const buffered=new Request(original.url,{method:'POST',headers:original.headers,body:await original.arrayBuffer()});assert.equal((await POST(buffered)).status,413);assert.equal(smtpCalls,0);});
test('trusted IP required and IPv6 normalized',()=>{assert.throws(()=>security.clientIp(new Request('https://eden.test')));assert.equal(security.clientIp(new Request('https://eden.test',{headers:{'x-forwarded-for':'2001:db8:0:0:0:0:0:1'}})),'[2001:db8::1]');});
